In [33]:
import numpy as np

In [34]:
import pandas as pd


In [35]:
quina_loterica = '/content/Quina.xlsx'

In [36]:
quina = pd.read_excel(quina_loterica)

In [37]:
quina.head()

Concurso Data Sorteio  Bola1  Bola2  Bola3  Bola4  Bola5  \
0         1   13/03/1994     25     45     60     76     79   
1         2   17/03/1994     13     30     58     63     64   
2         3   20/03/1994      5     15     32     33     48   
3         4   24/03/1994     27     57     60     61     77   
4         5   27/03/1994     19     44     53     54     71   

   Ganhadores 5 acertos Cidade / UF  Rateio 5 acertos  ...  Rateio 4 acertos  \
0                     3         NaN   R$75.731.225,00  ...    R$1.788.927,00   
1                     1         NaN  R$118.499.397,00  ...    R$1.128.565,00   
2                     1         NaN  R$154.244.270,00  ...      R$664.846,00   
3                     1         NaN  R$124.185.246,00  ...    R$1.592.119,00   
4                     1         NaN  R$147.595.715,00  ...    R$1.077.341,00   

  Ganhadores 3 acertos  Rateio 3 acertos Ganhadores 2 acertos  \
0                 7030       R$42.982,00                    0   
1                 4861       R$32.422,00                    0   
2                10196       R$20.120,00                    0   
3                 4033       R$40.954,00                    0   
4                 5338       R$36.774,00                    0   

   Rateio 2 acertos Acumulado 5 acertos Arrecadacao Total Estimativa Premio  \
0            R$0,00              R$0,00            R$0,00            R$0,00   
1            R$0,00              R$0,00            R$0,00            R$0,00   
2            R$0,00              R$0,00            R$0,00            R$0,00   
3            R$0,00              R$0,00            R$0,00            R$0,00   
4            R$0,00              R$0,00            R$0,00            R$0,00   

  Acumulado Sorteio Especial Quina de São João observação  
0                                       R$0,00        NaN  
1                                       R$0,00        NaN  
2                                       R$0,00        NaN  
3                                       R$0,00        NaN  
4                                       R$0,00        NaN  

[5 rows x 21 columns]

In [17]:
quina.dtypes

Concurso                                         int64
Data Sorteio                                    object
Bola1                                            int64
Bola2                                            int64
Bola3                                            int64
Bola4                                            int64
Bola5                                            int64
Ganhadores 5 acertos                             int64
Cidade / UF                                     object
Rateio 5 acertos                                object
Ganhadores 4 acertos                             int64
Rateio 4 acertos                                object
Ganhadores 3 acertos                             int64
Rateio 3 acertos                                object
Ganhadores 2 acertos                             int64
Rateio 2 acertos                                object
Acumulado 5 acertos                             object
Arrecadacao Total                               object
Estimativa

In [38]:
bolaNumeros = quina[['Bola1','Bola2','Bola3','Bola4','Bola5']]

In [39]:
print(bolaNumeros)

      Bola1  Bola2  Bola3  Bola4  Bola5
0        25     45     60     76     79
1        13     30     58     63     64
2         5     15     32     33     48
3        27     57     60     61     77
4        19     44     53     54     71
...     ...    ...    ...    ...    ...
6260     44     52     63     71     77
6261     16     38     64     68     77
6262     26     27     34     36     60
6263      2      3     27     35     43
6264     48     52     53     67     78

[6265 rows x 5 columns]


In [40]:
duplicados = bolaNumeros[bolaNumeros.duplicated(subset=['Bola1','Bola2','Bola3','Bola4','Bola5'])]

In [41]:
contador = bolaNumeros[['Bola1','Bola2','Bola3','Bola4','Bola5']].value_counts()

In [42]:
print(duplicados)

      Bola1  Bola2  Bola3  Bola4  Bola5
1156      7     10     28     62     78
4308     14     35     37     57     65
5983     32     35     37     65     66


In [30]:
print(contador)

Bola1  Bola2  Bola3  Bola4  Bola5
32     35     37     65     66       2
14     35     37     57     65       2
7      10     28     62     78       2
1      2      3      27     65       1
16     18     42     54     61       1
                                    ..
7      8      18     25     35       1
              17     47     55       1
              13     49     65       1
                     18     24       1
66     73     75     76     79       1
Length: 6262, dtype: int64


In [43]:
matriz = bolaNumeros.values

In [44]:
print(matriz)

[[25 45 60 76 79]
 [13 30 58 63 64]
 [ 5 15 32 33 48]
 ...
 [26 27 34 36 60]
 [ 2  3 27 35 43]
 [48 52 53 67 78]]


In [46]:
# Obtém os valores únicos e suas contagens
valores_unicos, contagem = np.unique(matriz, return_counts=True)

# Cria um DataFrame para armazenar os valores únicos e suas contagens
dados_contagem = pd.DataFrame({'Valor': valores_unicos, 'Contagem': contagem})

# Ordena o DataFrame pela coluna 'Contagem' em ordem decrescente
dados_contagem = dados_contagem.sort_values(by='Contagem', ascending=False)

# Obtém os valores mais repetidos
valores_mais_repetidos = dados_contagem[dados_contagem['Contagem'] == dados_contagem['Contagem'].max()]

print("Valores mais repetidos:")
print(valores_mais_repetidos)

#O código acima cria um DataFrame chamado dados_contagem que armazena os valores únicos e suas contagens.
#Em seguida, ele classifica o DataFrame com base na coluna de contagem em ordem decrescente.
#Por fim, ele obtém os valores mais repetidos, que são aqueles com a contagem máxima.
#Os valores mais repetidos serão armazenados no DataFrame valores_mais_repetidos,
#que pode ser impresso ou usado conforme necessário.







Valores mais repetidos:
   Valor  Contagem
3      4       443


In [64]:
# Obtém os valores únicos e suas contagens
valores_unicos, contagem = np.unique(matriz, return_counts=True)

# Verifica quais valores têm contagens maiores que 1 (são repetidos)
valores_repetidos = valores_unicos[contagem > 420]

print("Valores repetidos:")
print(valores_repetidos)


Valores repetidos:
[ 4 16 26 49 52]
